version: 2.1

executors:
  rust-exec:
    docker:
      - image: rustlang/rust:nightly-slim

jobs:
  lint:
    executor: rust-exec
    steps:
      - checkout
      - run: cargo clippy -- -Drust-2018-idioms
  test:
    executor: rust-exec
    steps:
      - checkout
      - run: cargo install cargo2junit
      - run: mkdir -p ~/test-results/cargo
      - run: cargo test -- -Z unstable-options --format json | cargo2junit > ~/test-results/cargo/test-output.xml
      - store_test_results:
          path: ~/test-results

workflows:
  lint_and_test:
    jobs:
      - lint
      - test
