version: 2.1

executors:
  rust-exec:
    docker:
      - image: cimg/rust:1.48.0

jobs:
  lint:
    executor: rust-exec
    steps:
      - checkout
      - run: cargo clippy -- -Drust-2018-idioms
  test:
    executor: rust-exec
    steps:
      - checkout
      - run: cargo test

workflows:
  lint_and_test:
    jobs:
      - lint
      - test